### ISSUE TITLE
直接看二楼 

### ISSUE THREAD

**Issue by aclihub** [CatAndCoffee/playground#2]
经过我在寒假，仔细刻苦地学习我那一知半解的编程，运行又失败了。

首先我根据您说的

> 下载图片的时候可能需要更换urlImageBase变量的值 2019-02-07分到的分流服务器是http://n2.1whour.com/
2019-02-10分到的则是http://n8.1whour.com/ 理论上是不需要更换的，从哪个服务器下载都可以，但是如果真的无法下载，则需要你自己看一下你被分到哪个分流服务器了（访问图片链接就知道了）

然后我去找了图片页面
![2](https://user-images.githubusercontent.com/54567707/73153525-11f7f880-410f-11ea-9c1e-ee3d9de39d4e.png)
（链接：https://s1.kukudm.com/kuku4comic4/mkxdcdcp/Vol_01/kkdm006XEI.jpg）
修改了程序：urlImageBase = 'https://s1.kukudm.com'
然后再运行
就又会报错
![1](https://user-images.githubusercontent.com/54567707/73153543-220fd800-410f-11ea-835f-829cedb394eb.png)

> c:\Users\admin\Desktop\railgun>cd c:\Users\admin\Desktop\railgun && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && C:\Users\admin\AppData\Local\Programs\Python\Python36-32\python.exe c:\Users\admin\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\ptvsd_launcher.py --default --nodebug --client --host localhost --port 2677 c:\Users\admin\Desktop\railgun\railgun.py "
Traceback (most recent call last):
  File "c:\Users\admin\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\admin\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\admin\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\admin\Desktop\railgun\railgun.py", line 45, in <module>
    os.mkdir("./" + str(dirName))
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: './1某科学的超电磁炮_Vol_1'

运行后会得到的文件目录：
* railgun
  * 1某科学的超电磁炮_Vol_1
     * 1.jpg
     * 2.jpg
  * content.txt
  * railgun.py
两张图片都是这样（就是发生错误这样的图片）
![1](https://user-images.githubusercontent.com/54567707/73153472-effe7600-410e-11ea-95c8-d34f666efaf6.jpg)

**Comment by aclihub** [comment]
终于成功了，抱歉，又来打扰，今天又尝试。莫名其妙想装python 3.8及以上的版本，win7装不上，sp1明明在也没用，后来退而求其次，装了3.7，由于想起requests，又用pip重装了一次突然想到是不是以前的文件没删掉所引起，Shift+Delete删掉了之前运行出来的 1某科学的超电磁炮_Vol_1与 content.txt一并删掉，谁知这次竟然成功了（以前用这种方法是没用的）现在正在下载，黑琴万岁！！

**Comment by aclihub** [comment]
这个程序可以运行了，就是对方服务器估计不那么稳，所以程序会停止，而停止后就要把其爱安全部删掉才能重新下载
